# Generated by Django 5.0.6 on 2024-05-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='task',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
